name: Documentation

on:
    push:
      branches: [ "main" ]
    pull_request:
      branches: [ "main" ]
  
env:
    DOCS_DIR: doc
    PUBLISH_DOCS_DIR: ${{github.workspace}}/build/docs/html

    TESTLIB: testlib  # The name of the main entry point for tests
    TEST_DIR: test
    DEVELOPER_BUILD: Developer
  
jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    permissions:
        contents: write

    steps:
    - uses: actions/checkout@v3
    - uses: ssciwr/doxygen-install@v1

    - name: Configure Release 
      run: cmake -S ${{ github.workspace }} -B ${{ github.workspace }}/build

    - name: Doxygen Documentation Generation
      working-directory: ${{ github.workspace}}/build
      run: make docs

    - name: Deploy Documentation
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ${{ env.PUBLISH_DOCS_DIR }}